// <auto-generated />
namespace bsmAnalysis.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class aliperfectISAdesigner : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(aliperfectISAdesigner));
        
        string IMigrationMetadata.Id
        {
            get { return "201304271128019_aliperfectISAdesigner"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
